theme: jekyll-theme-slate

name: Bridge to Masters

description: Attempting to Democratize Graduate level Math and Programming

author : 
  name : Angel D'az
  email : angelddaz@gmail.com
  github : angelddaz
  twitter : angeld_az
  
BASE_PATH : http://kbroman.org/simple_site
